// Top-level build file
buildscript {
    repositories {
        // 阿里云镜像
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.4'
    }
}

plugins {
    id 'com.android.application' version '8.1.4' apply false
}

task clean(type: Delete) {
    delete rootProject.buildDir
}